{
	"version": 1648036949,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/sprite-sheet0.png",
		"images/enemy-sheet0.png",
		"images/bala-sheet0.png",
		"images/mensaje_fin-sheet0.png",
		"images/mensaje_fin-sheet1.png",
		"images/bandera-sheet0.png",
		"images/camera-sheet0.png",
		"images/fondo-sheet0.png",
		"images/suelo-sheet0.png",
		"images/player_image-sheet0.png",
		"images/player_image-sheet1.png",
		"images/enemy_image2-sheet0.png",
		"images/enemy_image2-sheet1.png",
		"media/happy 8bit loop 01 ©.ogg",
		"media/jump.m4a",
		"media/jump.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}