const Constantes= {
    EVETOS:{
        VIDAS:"cambiaVidas",
        PUNTUACION:"puntuacion"
    },
    MENU:{
        JUGAR:"JUGAR"
    },
    HUD:{
        VIDAS:"Vidas:"
    },
    ESCENAS:{
        MENU:"Menu",
        NIVEL1:"Nivel1",
        HUD:"HUD",
        CARGA:"Carga"
    },
    REGISTRO:{
        VIDAS:"vidas",
        PUNTUACION:"puntuacion"
    },
    MAPAS:{
        NIVEL1:{
            TILEMAPJSON:"mapaNivel1",
            CAPAPLATAFORMAS:"Plataformas"
        },
        TILESET:"nivelesTileSet"
    }
}
export default Constantes;